### ISSUE TITLE
Updates .... and suggestions to future

### ISSUE THREAD

**Issue by marmmc** [msartore/ATA-GUI#10]
an excellent software for mobile tweaking, but here are some tips for improvements...

1 - hide apps script
2 - chmod permissions boot android script
3 - extract script img files

some tips and improvements for future updates

**Comment by TomieAi** [comment]
i dont know if this is already added xD but how do i extract the apk or download it from my phone to my pc?

**Comment by msartore** [comment]
> i dont know if this is already added xD but how do i extract the apk or download it from my phone to my pc?

not implemented yet, if you can open an issue requesting it :)

**Comment by msartore** [comment]
@TomieAi now available https://github.com/msartore/ATA-GUI/releases/tag/v2.1.0

**Comment by msartore** [comment]
The following request:

> extract script img files

has been implemented in the [v3.7.2](https://github.com/msartore/ATA-GUI/releases/tag/v3.7.2), check it out!

**Comment by drogga** [comment]
@marmmc
As this is already a messy ticket (the closed ones aren't better), I decided to add my suggestions and delete this comment later if problematic.

Please add a custom `platform-tools` path input field in the settings, with or without a "browse" button, because mine purposely aren't "installed", so I have to keep this one's .exe in the root of the platform-tools folder and this is not an optimal solution for me.

It must also have a Dark Theme.

Please react with an emoji, like "eyes", so I know that you saw this. Thank You in advance.

**Comment by msartore** [comment]
> Please add a custom platform-tools path input field in the settings, with or without a "browse" button, because mine purposely aren't "installed", so I have to keep this one's .exe in the root of the platform-tools folder and this is not an optimal solution for me.

Just added the support for environment variables scanning on the latest release ![v3.8.0](https://github.com/msartore/ATA-GUI/releases/tag/v3.8.0). Let me know if everything works!

> It must also have a Dark Theme.
It will be added in the future

**Comment by drogga** [comment]
It automatically finds the platform-tools now [Thanks], but my idea was for their location path in the settings of ATA for the cases when the PATH is NOT added to the Environment Variables, just like the Wiki mentions `or specify the path within ATA-GUI's settings`, but I don't see such option, or it's only available/visible in certain scenarios _(like the PATH or the platform-tools folder missing from C:\, because I didn't play around much, testing without them for now)_...?

I have other similar tools on the machine I'm writing from _(and at least 2 other, very similar to ATA-GUI - I guess they are based on each other)_ and would like if you can implement a File Browser/Explorer, like the following have: adbGUI, ADB Explorer, Aow Tools, DroidDevBros & maybe ADB AppControl, along with their specific options, for example adbGUI (v.2.2) has the most (insane amount of - I haven't even used half of them), but I don't expect you to add all of them. ;)

**Comment by msartore** [comment]
> Location path in the settings of ATA for the cases when the PATH is NOT added to the Environment Variables

The custom path inside ATA-GUI's settings will be added in the future

> I guess they are based on each other 
This application is based on an [old script](https://github.com/msartore/Advance-Tool-for-Android-ADB-Tool) developed for Windows and Linux by me. Then I wanted to develop something more user-friendly, so I started to build on that base to add more and more features.

> implement a File Browser/Explorer
I thought about it, but I did not have time for it yet.

**Comment by drogga** [comment]
Please consider adding/mentioning the ver. of the asset files file name in /releases, instead of all being "ATA-GUI" - less confusing to have app name with ver. when DLing, not having to rename during or afterwards (or letting them automatically be renamed if you keep an older one with a number in brackets by the browser/download manager) ;)
